apiVersion: skatelescope.org/v1
kind: MPIJob
metadata:
  name: test-mpi
spec:
  replicas: ${REPLICAS}
  template:
    metadata:
      labels:
        mpi-app: do-the-thing
    spec:
      containers:
      - name: test-mpi
        image: ${MPIBASE_IMAGE}
        command: ["mpiexec"]
        args: [ '--allow-run-as-root',
                '--display-map',
                'sh', '-c', 'echo ${MYHOST}:hello']
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /mnt
            name: mount-data
            readOnly: true
      imagePullSecrets:
        - name: gitlab-registry
      volumes:
      - name: mount-data
        hostPath:
          path: /etc
          type: Directory
