{{ if .Values.controller.enabled }}
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mpijobs.skatelescope.org
spec:
  group: skatelescope.org
  version: v1
  scope: Namespaced
  names:
    plural: mpijobs
    singular: mpijob
    kind: MPIJob
    shortNames:
    - mj
    - mpij
  additionalPrinterColumns:
  - name: Replicas
    type: integer
    description: The number of Pods in the MPIJob
    JSONPath: .spec.replicas
  validation:
    openAPIV3Schema:
      properties:
        spec:
          title: The MPIJob spec
          description: replicas should be specified
          properties:
            replicas:
              title: Total number of replicas
              description: Required replicas for the MPI cluster
              type: integer
              minimum: 1
            slots:
              title: Number of slots per instance
              description: Number of slots per instance for the MPI cluster
              type: integer
              minimum: 1
            daemon:
              title: Daemon, strictly one per node
              description: Force MPI cluster to launch one per node
              type: boolean
          required:
          - replicas

{{ end }}
